## Dynamic configuration
http:
  services:
    app:
      weighted:
        services:
        - name: appv1
          weight: 6
        - name: appv2
          weight: 3
        - name: appv3
          weight: 1

    appv1:
      loadBalancer:
        servers:
        - url: "http://10.4.0.100"

    appv2:
      loadBalancer:
        servers:
        - url: "http://10.4.0.101"

    appv3:
      loadBalancer:
        servers:
        - url: "http://10.4.0.102"